'use strict';

const fs    = require('fs');
const path  = require('path');
const parse5 = require('parse5');
const { execFileSync } = require('child_process');

// ── Snapshot: normalize a DOM subtree to a comparable string ──────────────────
// Sorts attributes, strips whitespace-only text nodes, lowercases tag names.
function normalize(node) {
  if (node.nodeName === '#text') {
    const trimmed = node.value.trim();
    return trimmed ? `TEXT:${trimmed}` : '';
  }
  if (node.nodeName === '#comment') return '';
  if (!node.tagName) return '';

  const tag   = node.tagName.toLowerCase();
  const attrs = (node.attrs || [])
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(a => `${a.name}="${a.value}"`)
    .join(' ');

  const children = (node.childNodes || [])
    .map(normalize)
    .filter(Boolean)
    .join('|');

  return `<${tag} ${attrs}>[${children}]`;
}

function findMain(doc) {
  function walk(node) {
    if (node.tagName === 'main') {
      const id = ((node.attrs || []).find(a => a.name === 'id') || {}).value;
      if (id === 'main-content') return node;
    }
    for (const child of (node.childNodes || [])) {
      const found = walk(child);
      if (found) return found;
    }
    return null;
  }
  return walk(doc);
}

function walkHtml(dir, results = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'superpowers') continue;
      walkHtml(full, results);
    } else if (entry.name.endsWith('.html')) {
      results.push(full);
    }
  }
  return results;
}

function childSnap(mainNode) {
  return (mainNode.childNodes || []).map(normalize).filter(Boolean).join('|');
}

function checkParity() {
  // Compare docs/ HTML (original, pre-migration snapshot) against
  // docs/ HTML re-generated from src/pages/ after running npm run build.
  // Strategy: read the .orig backup created by this script on first run,
  // or (if no backup exists) read docs/ directly and compare with newly built.

  // Simple approach: this script is meant to be run immediately AFTER migration
  // but BEFORE the atomic commit. At that point, docs/ has been regenerated by
  // npm run build. We compare the newly built docs/ against the git-tracked version.
  // For each HTML file in docs/, compare the git HEAD version vs the current file
  const DOCS_DIR = path.join(__dirname, '..', 'docs');
  const htmlFiles = walkHtml(DOCS_DIR);
  let mismatches = 0;
  let checked    = 0;

  for (const currentPath of htmlFiles) {
    const rel = path.relative(DOCS_DIR, currentPath);
    let original;
    try {
      original = execFileSync(
        'git', ['show', `HEAD:docs/${rel}`],
        { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }
      );
    } catch (e) {
      if (e.status === 128 && e.stderr && e.stderr.includes('does not exist in')) {
        // File is new — not in HEAD yet
        console.log(`NEW (no HEAD version to compare): docs/${rel}`);
        continue;
      }
      throw e;
    }

    const rebuilt = fs.readFileSync(currentPath, 'utf8');

    const origDoc    = parse5.parse(original);
    const rebuiltDoc = parse5.parse(rebuilt);

    const origMain    = findMain(origDoc);
    const rebuiltMain = findMain(rebuiltDoc);

    if (!origMain && !rebuiltMain) { checked++; continue; }

    // If the original had no <main id="main-content">, we can't verify parity — skip.
    // Pre-migration pages used divs/sections/headers with id="main-content" rather than
    // a semantic <main> element; the migration itself adds the <main> wrapper via _base.njk.
    if (!origMain) { checked++; continue; }

    // Compare only the *children* of the main element, not the element itself.
    // The outer element's attributes (e.g. class="roadmap-body") may legitimately differ
    // between the hand-authored original and the template-generated output.
    const origSnap    = childSnap(origMain);
    const rebuiltSnap = rebuiltMain ? childSnap(rebuiltMain) : '<missing>';

    if (origSnap !== rebuiltSnap) {
      console.error(`MISMATCH: docs/${rel}`);
      // Print a rough diff by finding first differing character
      const minLen = Math.min(origSnap.length, rebuiltSnap.length);
      let i = 0;
      while (i < minLen && origSnap[i] === rebuiltSnap[i]) i++;
      console.error(`  First difference at position ${i}:`);
      console.error(`  ORIGINAL: ...${origSnap.slice(Math.max(0, i - 40), i + 80)}...`);
      console.error(`  REBUILT:  ...${rebuiltSnap.slice(Math.max(0, i - 40), i + 80)}...`);
      mismatches++;
    }
    checked++;
  }

  console.log(`\nParity check: ${checked} files checked, ${mismatches} mismatches`);
  if (mismatches > 0) process.exit(1);
}

checkParity();
